holoviz/spatialpandas

- NOTICE
- setup.py
- spatialpandas/__init__.py
- spatialpandas/spatialindex/__init__.py
- spatialpandas/spatialindex/hilbert_curve.py
- spatialpandas/spatialindex/rtree.py
- spatialpandas/utils.py
- tests/spatialindex/hilbert_curve.py
- tests/spatialindex/rtree.py
This PR provides a numba accelerated implementation of a Hilbert R-tree. See https://en.wikipedia.org/wiki/Hilbert_R-tree for more info on the Hilbert R-tree.
This implementation stores the R-tree as an array representation of a binary tree. See https://en.wikipedia.org/wiki/Binary_tree#Arrays for more info on the array representation of a binary tree. This representation was selected because it is very memory efficient for read-only binary trees.
Future PRs will use this functionality to provide numba implementations of spatial indexing and spatial joins at the pandas and Dask data frame level.
I benchmarked this implementation against the `rtree` package in the notebook at https://anaconda.org/jonmmease/spatialpandas_hilbertrtree_benchmarking_pr/notebook.  Both the R-tree creation and …
> Add numba implementation of a Hilbert R-tree

- spatialpandas/__init__.py
- spatialpandas/dask.py
- spatialpandas/geodataframe.py
- spatialpandas/geometry/_algorithms/orientation.py
- spatialpandas/geometry/base.py
- spatialpandas/geometry/line.py
- spatialpandas/geometry/multiline.py
- spatialpandas/geometry/multipoint.py
- spatialpandas/geometry/multipolygon.py
- spatialpandas/geometry/polygon.py
- spatialpandas/geoseries.py
- spatialpandas/io/__init__.py
- spatialpandas/io/parquet.py
- spatialpandas/spatialindex/rtree.py
- tests/geometry/algorithms/intersection.py
- tests/geometry/algorithms/measures.py
- tests/geometry/test_cx.py
- tests/spatialindex/rtree.py
- tests/test_extensionarray.py
- tests/test_geodataframe.py
- tests/test_parquet.py
This PR introduces four new classes. `GeoSeries` and `GeoDataFrame` are subclasses of pandas `Series` and `DataFrame` respectively. I used the geopandas class names because I was able to use a subset of the geopandas API in these classes.
The `DaskGeoSeries` and `DaskGeoDataFrame` classes are subclasses of dask `Series` and `DataFrame` respectively.
The `GeoDataFrame` and `DaskGeoDataFrame` classes use the geopandas concept
of an active geometry column to control which column `cx` applies to (discussed below).
The most interesting part part of this PR, in my opinion, is the `cx` indexer on `DaskGeoSeries` and `DaskGeoDataFrame`.   These classes support a distributed `cx` that use a two layer R-tree.
- A top-level R-tree is used to identify which partitions to include. These partitions are …
> Add GeoSeries, GeoDataFrame, DaskGeoSeries, and DaskGeoDataFrame classes

- spatialpandas/geometry/__init__.py
- spatialpandas/geometry/base.py
- spatialpandas/geometry/basefixed.py
- spatialpandas/geometry/baselist.py
- spatialpandas/geometry/basestruct.py
- spatialpandas/geometry/point.py
- spatialpandas/io/parquet.py
- tests/geometry/algorithms/test_intersection.py
- tests/geometry/strategies.py
- tests/geometry/test_construction.py
- tests/geometry/test_cx.py
- tests/geometry/test_geometry.py
- tests/geometry/test_to_geopandas.py
- tests/test_fixedextensionarray.py
- tests/test_parquet.py
This PR adds a `PointArray` geometry type for the storage of individual points. These are backed by pyarrow fixed width binary arrays.  Like the rest of the geometry types, these support serialization to and from parquet.
> Add fixed length PointArray type

- setup.py
Closes https://github.com/holoviz/spatialpandas/issues/15 by adding the example dependencies to `extras_require` in setup.py, and as a comment in the Overview notebook.
> Document optional dependencies for Overview notebook

- setup.py
- spatialpandas/dask.py
- spatialpandas/geoseries.py
- spatialpandas/io/parquet.py
- spatialpandas/io/utils.py
- tests/test_parquet.py
This PR adds a new `DaskGeoDataFrame.pack_partitions_to_parquet` method.  This method is equivalent to chaining `pack_partitions` and `to_parquet`, but it has lower memory requirements.
> Add pack partitions to parquet method

- CHANGELOG.md
- spatialpandas/dask.py
- spatialpandas/io/parquet.py
- spatialpandas/io/utils.py
- tests/test_dask_autoimport.py
- tests/test_parquet.py
This PR rewrites `read_parquet_dask` to:
- Add support for specifying a list of paths or a glob string path that matches 1 or more paths.  
- Add a `bounds` argument to restrict partitions to those that intersect with the specified bounding box
It also adds a fix and test to make sure that the `DaskGeoDataFrame` is registered with Dask when `spatialpandas` is imported.
> Add glob support and bounding box filter to read_parquet_dask

- spatialpandas/dask.py
- spatialpandas/io/parquet.py
- tests/test_parquet.py
This PR adds a new argument to `DaskGeoDataFrame.pack_partitions_to_parquet` named `temp_format`.  This argument may be set to a format string containing a `{partition}` replacement field. If provided, this string is formatted with the output partition number to generate the temporary directory path for that partition.
For example `temp_format="/tmp/spatial/part-{partition}"` would create temporary directories:
-  `/tmp/spatial/part-0`
-  `/tmp/spatial/part-1`
-  `/tmp/spatial/part-2`
...
The `temp_format` string may also contain a `{uuid}` replacement field. If provided this will be replaced by a randomly generated UUID string.  This makes it possible to reuse the same `temp_format` string in multiple simultaneous jobs without conflict.
> Add temp_format argument to pack_partitions_to_parquet

- spatialpandas/io/parquet.py
- spatialpandas/spatialindex/rtree.py
- spatialpandas/tools/sjoin.py
- tests/test_parquet.py
- tests/tools/test_sjoin.py
This PR improves the efficiency of the spatial join algorithm for the case where the left frame is a `DaskGeoDataFrame` and the right frame is a `GeoDataFrame`.
Now, we iterate over the partitions of the left frame and use the partition bounding box to extract the candidate rows from the right frame (using the right frame's spatial index). If no rows are selected while performing an `inner` join, the partition is skipped altogether.
722ca87  also adds a fix to make sure that that pyarrow parquet parts are sorted properly when loading a parquet file.
> spatial join Dask updates

- CHANGELOG.md
- setup.py
- spatialpandas/dask.py
- spatialpandas/io/parquet.py
A few fixes for 0.3.1:
- Add categories kwarg to `read_parquet_dask` to work around dask/dask#5677
- Use the `retrying` library to retry filesystem operations in `pack_partitions_to_parquet` 
- Fix for loading multiple parquet files with a glob string while using a filesystem with protocol.
> categorical fix and retry filesystem operations

- .travis.yml
- CHANGELOG.md
- setup.py
- spatialpandas/dask.py
- spatialpandas/geometry/base.py
- spatialpandas/io/parquet.py
- spatialpandas/spatialindex/rtree.py
- spatialpandas/tools/sjoin.py
- tests/test_fixedextensionarray.py
- tests/test_listextensionarray.py
- tests/test_parquet.py
Closes #34, #35, #36
If possible, and if this is accepted, it would be helpful to cut a new release once merged.
> Minor fixes

- .travis.yml
- setup.py
- spatialpandas/geometry/base.py
- spatialpandas/geometry/baselist.py
- tests/test_fixedextensionarray.py
- tests/test_listextensionarray.py
- tests/test_parquet.py
This PR adds support for `pyarrow` 1.0, maintaining compatibility with the currently working pre-1.0 versions of `pyarrow`.
It also removes the upper pyarrow constraint bounds from the setup.py metadata and the CI test environment.
Closes https://github.com/holoviz/spatialpandas/issues/43
> Add pyarrow 1.0 and pandas 1.1 support

- spatialpandas/geometry/base.py
- tests/geometry/test_construction.py
- tests/test_parquet.py
Fixes #47.  
Also fixes a heavily repeated warning from Hypothesis about usage of tmp_path by using a context manager, which required indenting large blocks of code and making changes to `tests/test_parquet.py` appear more numerous than actual.
The number of warnings during testing reduced from 37,752 warnings to 195.
> Fix various warnings

- spatialpandas/dask.py
- spatialpandas/geodataframe.py
- spatialpandas/geometry/base.py
- spatialpandas/geoseries.py
- spatialpandas/io/parquet.py
The problem with using `cx` on a DaskGeoDataFrame was that it would use `cx` on each partition which in turn would spatially index that partition because it was using the `sindex` attribute. It seems as though these spatial indexing wouldn't persist either so every time you did some indexing it would create a completely new `sindex` slowing down the indexing massively. I now only use the sindex if it already exists. I would like there to be a more explicit API on GeometryArrays, GeoSeries, GeoDataFrames, DaskGeoSeries and DaskGeoDataFrame that says "create an spatial index" rather than using the implicit behavior of creating a spatial index when `sindex` is accessed.
> Allow using cx indexer without spatial index

- README.md
This will prevent an extra set of `()` from being displayed in the README and (once this PR is merged) will hopefully allow me to run CI builds over in https://github.com/holoviz/spatialpandas/pull/70 without maintainer approval
> Remove extra parenthesis from README

- .github/workflows/test.yml
- setup.py
- spatialpandas/dask.py
This PR adds some compatibility updates for the `dask=2021.06.0` release. xref https://github.com/dask/dask/pull/7743#issuecomment-853693448
cc @jbednar
Supersedes https://github.com/holoviz/spatialpandas/pull/69, xref https://github.com/holoviz/spatialpandas/issues/68#issuecomment-855285094
> Add compatibility for Dask 2021.06.0

- .github/workflows/build.yaml
- .github/workflows/test.yaml
@ianthomas23 I hope this is not stepping on your toes, I noticed that the [status dashboard](https://status.holoviz.org/) wasn't reporting the test state as the workflow was not running on master. I took the opportunity to make a few other changes so that the repo is a little more inline with the other repos, by:
- Allowing the workflows to be launched manually, only in dry-run mode for the packages build workflow
- Having the workflows run on Sundays
> CI: make the workflows more consistent with the other HoloViz packages 

- .github/workflows/test.yaml
- spatialpandas/tests/test_fixedextensionarray.py
- spatialpandas/tests/test_listextensionarray.py
This PR fixes the errors related to ragged arrays being pandas extension arrays which have had extra tests added. The "fixes" are all to disable those tests as the functionality does not apply to our ragged arrays.
Also temporarily limited github actions to only run testing on Python 3.8 on Linux until I have dealt with all of the current errors.
> Extension array fixes

- spatialpandas/tests/geometry/strategies.py
Candidate fix for failed geometry tests to see if CI is happy with it.
Before this PR, I was experiencing failed geometry intersection tests such as when running
```
pytest spatialpandas/tests/geometry/algorithms/test_intersection.py::test_segment_intersects_point
```
This tests if a 2D point lies on a straight line segment or not. It tests the line one way, then the other, then compares the result with that obtained from `shapely`. For some small values, an example being a point that is `2e-17` from one of the end points of the line segment, the test fails.
The failure is not surprising. Our point on line test is not geometrically robust (https://en.wikipedia.org/wiki/Robust_geometric_computation) so it is not surprising that it cannot cope with some small floating point differences. We …
> Remove failed geometry tests

- .github/workflows/build.yaml
- README.md
- setup.py
1. Update build status badge in README to link to the correct URL.
2. Add badge showing Python version supported. This will display correctly after the next release when PyPI metadata is updated.
3. Add project classifiers, in particular versions of Python supported.
4. Update `maintainer` and `maintainer_email`.
> Update README badges and project metadata

- .github/workflows/build.yaml
- CHANGELOG.md
This PR adds CHANGELOG entries for the v0.4.4 release, and updates the package building workflow in line with the testing workflow.
The intention is to release v0.4.4 today as it has been almost a year since the previous release, then we can address the remaining issues and pull requests as part of a regular ongoing maintenance and release strategy.
> Changelog and package build improvements for v0.4.4 release

- spatialpandas/tests/test_fixedextensionarray.py
- spatialpandas/tests/test_listextensionarray.py
Current failures in CI:
```
FAILED spatialpandas/tests/test_fixedextensionarray.py::TestGeometryMissing::test_fillna_series
FAILED spatialpandas/tests/test_fixedextensionarray.py::TestGeometryMissing::test_fillna_frame
FAILED spatialpandas/tests/test_listextensionarray.py::TestGeometryMissing::test_fillna_series
FAILED spatialpandas/tests/test_listextensionarray.py::TestGeometryMissing::test_fillna_frame
```
The original errors are:
```
NotImplementedError: <class 'spatialpandas.geometry.line.LineArray'> does not implement __setitem__.
```
So, as usual with new pandas ExtensionArray tests we skip them as we do not support this specific functionality.
> Skip test_fillna_frame and test_fillna_series extension array tests

- .github/workflows/test.yaml
- setup.py
- spatialpandas/geometry/multipolygon.py
- spatialpandas/geometry/polygon.py
Potential fix for #102. The code change is to avoid using `numpy` arrays with `dtype=object` as `shapely` 2.0 quite rightly is not expecting this.
> Don't use dtype=object when converting arrays to pass to shapely 2

- spatialpandas/geometry/basefixed.py
- spatialpandas/io/parquet.py
- spatialpandas/utils.py
Fixes #106 and #49.
Implicit conversion of a ragged array (sequence of numpy arrays with incompatible shapes) in numpy 1.24 raises a `ValueError` rather than a warning.  This is a solution to the problem inspired by https://github.com/holoviz/geoviews/pull/608 (thanks @Hoxbro). It is slightly more complicated than that GeoViews fix because we cannot test with numpy 1.24 until numba supports it, so here I am converting the warning that occurs for numpy < 1.24 into an error so that it is handled in the same way and in the same code path as the numpy >= 1.24 fix.
This PR also fixes the following warning:
```
FutureWarning: ``gather_statistics`` is deprecated and will be removed in a future release. Please use ``calculate_divisions`` instead.
```
> Support numpy 1.24 ragged array conversion

- spatialpandas/io/parquet.py
Fixes #109.
Test suite passes using latest `pyarrow == 11.0.0`.
Fix isn't quite as simple as removing the final use of `validate_schema` keyword argument. It was also necessary when identifying which columns to read from the parquet file to check which are classified as columns rather than indexes. I have also simplified the code a bit as it no longer needs a separate load of the `metadata` before creating the `ParquetDataset`.
This fix works for `pyarrow >= 5` (July 2021). I will try out another PR to support earlier `pyarrow` but the changes will be wider-ranging as there are a number of places in the code that do not currently support `pyarrow < 5` before this PR is considered.
> Remove all use of parquet's validate_schema

- spatialpandas/io/parquet.py
This PR provides support for all version of `pyarrow` from `1.0.0` (July 2020) to the latest `11.0.0` (January 2023). I have tested it locally on the following versions of `pyarrow`, and have also included the versions of `dask` and `pandas` used:
| pyarrow  | dask | pandas |
| --- | --- | --- |
| 11.0.0 | 2023.3.1 | 1.5.3 |
| 10.0.1 | 2023.3.1 | 1.5.3 |
| 9.0.0 | 2023.3.1 | 1.5.3 |
| 8.0.0 | 2023.3.1 | 1.5.3 |
| 7.0.0 | 2023.3.1 | 1.5.3 |
| 6.0.1 | 2023.3.1 | 1.5.3 |
| 5.0.0 | 2023.3.1 | 1.5.3 |
| 4.0.1 | 2022.7.1 | 1.5.3 |
| 3.0.0 | 2022.7.1 | 1.5.3 |
| 2.0.0 | 2022.7.1 | 1.5.3 |
| 1.0.1 | 2022.7.1 | 1.5.3 |
| 1.0.0 | 2022.7.1 | 1.3.5 |
> Support pyarrow back to version 1.0.0

- .github/workflows/test.yaml
Cancel concurrent jobs to avoid bogging down CI across the holoviz org.
> Cancel concurrent test workflows

- setup.py
To make spatialpandas pip installable from PyPI on Python 3.11 without the `python-snappy` dependency.
Fixes #116
> Set python-snappy as optional dependency

- spatialpandas/tests/test_parquet.py
CI is reporting
```
DeprecationWarning: pathlib.Path.__enter__() is deprecated and scheduled for removal in Python 3.13; Path objects as a context manager is a no-op
```
This PR replaces their use as context managers with direct assignment to a variable which is functionally as the context manager is a no-op.
> Remove pathlib.Path.__enter__ deprecation warnings

- .github/workflows/test.yaml
Switching Github Actions to use `holoviz_tasks/install` in line with other holoviz repos.
> Use holoviz_tasks/install action for CI

- setup.py
- spatialpandas/geodataframe.py
- spatialpandas/geoseries.py
Resolves #124
Don't know how big of a fan I am of the fix for recursion error, but it is a start.
> Support Pandas 2.1

- .github/workflows/build.yaml
There is a warning in the Build PyPI Packages github action:
```
The `python-version` input is not set. The version of Python currently in `PATH` will be used.
```
This PR fixes it.
> Set python version in Build PyPI Packages github action

- spatialpandas/geometry/base.py
- spatialpandas/tests/test_fixedextensionarray.py
- spatialpandas/tests/test_listextensionarray.py
This removes many but not all Pandas 2.1 future warnings.
> Remove some pandas 2.1 future warnings

- examples/Polygon-Array-Construction-From-Exterior.ipynb
- spatialpandas/geometry/base.py
- spatialpandas/geometry/multipolygon.py
- spatialpandas/geometry/polygon.py
- spatialpandas/tests/geometry/test_geometry.py
Closes #122 
- Introduces the `PolygonArray.from_exterior_coords()` and `MultiPolygonArray.from_exterior_coords()` class methods, which take-in an list/array of exterior coordinates equivalent to the following which are derived from Shapely Polygons/MultiPolygons
https://github.com/holoviz/spatialpandas/blob/dd941f2f5f6994c6f09996e9b8af315e16d00051/spatialpandas/geometry/polygon.py#L40-L42
https://github.com/holoviz/spatialpandas/blob/dd941f2f5f6994c6f09996e9b8af315e16d00051/spatialpandas/geometry/multipolygon.py#L40-L48
In [UXarray](https://github.com/UXARRAY/uxarray), we use SpatialPandas paired with Datashader to visualize geoscience data that resides on unstructured grids as Polygons. Our unstructured grid is represented as a set of connectivity and coordinate arrays, which we would …
> Construct `PolygonArray` or `MultiPolygonArray` from Exterior Coordinates 

- .github/workflows/build.yaml
It's been broken for a few months. I tested it by running the workflow against this branch in dry-run mode.
> Build: fix the PyPI workflow

- spatialpandas/io/parquet.py
The test suite has been broken for a few weeks with:
```
ValueError: Invalid pattern: '**' can only be an entire path component
```
This is due to a recent change in fsspec (https://github.com/fsspec/filesystem_spec/pull/1382), forcing `**` to be used between path separators only. I checked the change with the latest version of fsspec and a version before this breaking change, it works fine in both cases.
I believe spatialpandas will need a new release.
> Adapt glob to be compatible with the latest fsspec version

- spatialpandas/spatialindex/hilbert_curve.py
Basic this is failing on datashader, note it only fails when numba is disabled.
``` python
import os 
os.environ['NUMBA_DISABLE_JIT'] = '1' 
from numba import jit
import numpy as np
ngjit = jit(nopython=True, nogil=True)
bin_vec = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
dtype=np.uint8)
@ngjit
def _binary_2_int(bin_vec):
"""Convert a binary byte array to an integer"""
res = 0
next_val = 1
width = len(bin_vec)
for i in range(width):
res += next_val*bin_vec[width - i - 1]
next_val <<= 1
return res
_binary_2_int(bin_vec)
```
``` python-traceback
OverflowError                             Traceback (most recent call last)
Cell In[4], line 18
15         next_val <<= 1
16     return res
---> 18 _binary_2_int(bin_vec)
Cell In[4], line 13, in _binary_2_int(bin_vec)
10 …
```
> Convert to int to not break datashader CI for numpy 2

- pixi.toml
- pyproject.toml
- spatialpandas/dask.py
- spatialpandas/geodataframe.py
- spatialpandas/geoseries.py
- spatialpandas/io/parquet.py
- spatialpandas/tests/geometry/strategies.py
- spatialpandas/tests/spatialindex/test_hilbert_curve.py
- spatialpandas/tests/spatialindex/test_rtree.py
- spatialpandas/tests/test_fixedextensionarray.py
- spatialpandas/tests/test_listextensionarray.py
- spatialpandas/tests/test_parquet.py
Fixes #137
The pandas 2.2 compatibility changes are almost the same as those done in GeoPandas:
- https://github.com/geopandas/geopandas/pull/3046
- https://github.com/geopandas/geopandas/pull/3080
- https://github.com/geopandas/geopandas/pull/3234
- https://github.com/geopandas/geopandas/pull/3173
The dask warning was added in dask 2024.1:
- https://github.com/dask/dask/pull/10738
Removed legacy pyarrow support as we now lower pin to version 10
I have also added `HYPOTHESIS_MAX_EXAMPLES` to make it easier to test locally. 
Added `packaging` as a required dependency.
> Support Pandas 2.2, unpin Pyarrow, and fail on warnings in tests

- spatialpandas/tests/geometry/strategies.py
Fixes https://github.com/holoviz/spatialpandas/issues/152
The original example came down to this:
```
ax0 = 1.0
ay0 = -16.0
ax1 = 0.0
ay1 = 0.0
bx0 = 0.0
by0 = -1e-15
bx1 = 0.0
by1 = -1.0
triangle_orientation(ax0, -16.0, ax1, ay1, bx0, by0), triangle_orientation(ax0, -17.0, ax1, ay1, bx0, by0)  #Returns True, False
```
Which could further be reduced to this precision problem:
Now, we round the floats to one above the computer precision of numpy floats (for me, 15).
> Update resolution for floats in tests

- spatialpandas/tests/geometry/algorithms/test_intersection.py
Seeing this test fail regularly, with input as not being a line but only a point
> test: Don't compare line length of zero size

- spatialpandas/__init__.py
Previous if some import failed in `import spatialpandas.dask` there was no way to see it. It was leading to weird behavior.
> bug: use find_spec for spatialpandas.dask import

- spatialpandas/io/parquet.py
- spatialpandas/tests/test_parquet.py
It makes it so that the following will give the same types before it returned `(string[pyarrow], object)`.
``` python
import dask
import spatialpandas.io as sio
dask.config.set({"dataframe.convert-string": True})
ddf = sio.read_parquet_dask("./data/nyc_buildings.parq")
ddf["type"].dtype, ddf["type"].compute().dtype
```
Together with https://github.com/holoviz/holoviews/pull/6362 should make it possible to run the NYC Buildings example.
> compat: Ensure that pandas dtype matches dask when loading data from parquet

- pixi.toml
- pyproject.toml
The classic dask.dataframe implementation no longer works; this adds an upper pin for the last version that supported it. This makes our test fail
https://github.com/holoviz/spatialpandas/actions/runs/12849469027/job/35828212336
It can be removed when https://github.com/holoviz/spatialpandas/issues/146 is merged.
> compat: Upper pin Dask

- .github/workflows/test.yaml
- pixi.toml
- pyproject.toml
- spatialpandas/dask.py
- spatialpandas/io/parquet.py
Resolves https://github.com/holoviz/spatialpandas/issues/146 
Resolves https://github.com/holoviz/spatialpandas/issues/169
I don't want to support the legacy method, so I'm pinning to 2025.1, the first version with the dask-expr part of the dask library.  This version only supports Python 3.10 and forward.
I haven't done any performance benchmarks. This is only to get spatialpandas to work with dask going forward.
reference: https://docs.dask.org/en/stable/dataframe-extend.html
The main functionality has been tested for both HoloViews and Datashader here:
- https://github.com/holoviz/holoviews/pull/6503
- https://github.com/holoviz/datashader/pull/1405
> compat!: Support dask query-planning, drop Python 3.9, update pins

- pixi.toml
Sometimes the example tests fail, this is an attempt to fix it.
> ci: Add `MALLOC_TRIM_THRESHOLD_` for test-example
